export const FETCH_EVENTS = 'EVENTS/FETCH_ALL';
export const FETCH_EVENTS_SUCCESS = 'EVENTS/FETCH_ALL_SUCCESS';
export const FETCH_EVENTS_FAIL = 'EVENTS/FETCH_ALL_FAIL';

export const FETCH_EVENT_BY_URL = 'EVENTS/FETCH_BY_URL';
export const FETCH_EVENT_BY_URL_SUCCESS = 'EVENTS/FETCH_BY_URL_SUCCESS';
export const FETCH_EVENT_BY_URL_FAIL = 'EVENTS/FETCH_BY_URL_FAIL';

export const CHECKOUT_EVENT_TICKETS = 'EVENTS/CHECKOUT_TICKETS';
export const CHECKOUT_EVENT_TICKETS_SUCCESS = 'EVENTS/CHECKOUT_TICKETS_SUCCESS';
export const RELEASE_EVENT_TICKETS = 'EVENTS/RELEASE_TICKETS';
export const RELEASE_EVENT_TICKETS_SUCCESS = 'EVENTS/RELEASE_TICKETS_SUCCESS';
export const CONFIRM_EVENT_TICKETS = 'EVENTS/CONFIRM_TICKETS';
export const CONFIRM_EVENT_TICKETS_SUCCESS = 'EVENTS/CONFIRM_TICKETS_SUCCESS';
export const RESET_EVENT_CONFIRM_REFERENCE_ID = 'EVENTS/RESET_CONFIRM_REFERENCE_ID'
export const WS_EVENT_TICKETS = 'EVENTS/WS_EVENT_TICKETS';
